from __future__ import annotations

import hashlib
import json
from datetime import date

from astro_abm_api.models.report import (
    DailyScenarioSnapshot,
    ScenarioReport,
    WorldlineAgentEvent,
    WorldlineCausalLink,
    WorldlineDay,
    WorldlineGenerationConfig,
    WorldlineImpactScores,
    WorldlineSimulation,
    WorldlineState,
)


WORLDLINE_DISCLAIMER = (
    "Simulated worldline only; scenario rehearsal only; not financial advice; "
    "not a trading signal."
)
WORLDLINE_DISCLAIMER_ZH_HANT = (
    "僅為模擬世界線；僅為情境推演；不構成財務建議；不是交易訊號。"
)


def clamp_pressure(value: float) -> float:
    return round(max(0.0, min(1.0, value)), 3)


def clamp_delta(value: int) -> int:
    return max(-2, min(2, int(value)))


def hash_worldline_state(state: WorldlineState) -> str:
    payload = state.model_dump(mode="json")
    encoded = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def ensure_worldline_state_continuity(days: list[WorldlineDay]) -> list[WorldlineDay]:
    ordered = sorted(days, key=lambda day: day.date)
    if not ordered:
        return []

    continuous = [ordered[0]]
    previous_state = ordered[0].world_state_after
    pressure_fields = (
        "narrative_pressure",
        "leverage_pressure",
        "liquidity_pressure",
        "volatility_pressure",
        "stress_pressure",
    )
    for day in ordered[1:]:
        if day.world_state_before == previous_state:
            continuous.append(day)
            previous_state = day.world_state_after
            continue

        pressure_updates = {
            field: clamp_pressure(
                getattr(previous_state, field)
                + getattr(day.world_state_after, field)
                - getattr(day.world_state_before, field)
            )
            for field in pressure_fields
        }
        rebased_after = day.world_state_after.model_copy(update=pressure_updates)
        continuity_note = (
            "World state was rebased from the previous day's output while preserving "
            "this day's pressure deltas."
        )
        rebased_day = day.model_copy(
            update={
                "world_state_before": previous_state,
                "world_state_after": rebased_after,
                "quality_notes": list(dict.fromkeys([*day.quality_notes, continuity_note])),
            }
        )
        continuous.append(rebased_day)
        previous_state = rebased_after
    return continuous


def generate_worldline_simulation(
    report: ScenarioReport,
    *,
    chunk_days: int = 3,
) -> WorldlineSimulation | None:
    if not report.daily_timeline:
        return None

    asset_support_by_date = _asset_support_by_date(report)
    language = report.language or "en"
    initial_state = _initial_state(
        report.daily_timeline[0],
        asset_support_by_date,
        language=language,
    )
    days = generate_worldline_days_for_range(
        report,
        start_date=report.daily_timeline[0].date,
        end_date=report.daily_timeline[-1].date,
        previous_state=initial_state,
        generation_source="deterministic_mock",
        chunk_index=None,
        chunk_status="mock_completed",
        quality_notes=(
            ["由確定性 mock 世界線規則生成。", "當日未執行 LLM 網路呼叫。"]
            if language == "zh-Hant"
            else [
                "Generated by deterministic mock worldline rules.",
                "No LLM network call was performed for this day.",
            ]
        ),
    )

    return WorldlineSimulation(
        status="mock_completed",
        mode="deterministic_mock_v1",
        horizon_days=len(days),
        days=days,
        summary=(
            "確定性 mock 世界線由每日時間線脈絡、群體狀態、資料覆蓋訊號及可用的資產壓力指標建立。"
            if language == "zh-Hant"
            else (
                "Deterministic mock worldline built from daily timeline context, "
                "agent states, coverage signals, and available asset stress indicators."
            )
        ),
        caveats=(
            [
                "模擬因果鏈是情境內部機制，不是真實因果的證據。",
                "壓力更新是只供未來推演使用的確定性 mock 數值。",
                "此層不抓取外部資料，也不呼叫 LLM。",
            ]
            if language == "zh-Hant"
            else [
                "Simulated causal links are scenario mechanics, not evidence of true causality.",
                "Pressure updates are deterministic mock values for future rehearsal only.",
                "This layer does not fetch external data and does not call an LLM.",
            ]
        ),
        provenance={
            "engine": "worldline_deterministic_mock_v1",
            "generation_mode": "deterministic_mock_v1",
            "source": "scenario_daily_timeline",
            "provider": "mock",
            "model": None,
            "prompt_template_version": None,
            "chunk_size_days": None,
            "network_call_performed": False,
            "input_context_hash": "",
            "output_validation_status": "not_run",
            "safety_check_status": "not_run",
            "credential_status": "not_configured",
            "chunk_count": 0,
            "failed_chunk_count": 0,
            "external_calls": False,
        },
        generation_config=WorldlineGenerationConfig(
            worldline_provider="deterministic_mock",
            worldline_chunk_days=chunk_days,
            llm_provider="mock",
            report_language=report.language,
            credential_status="not_configured",
        ),
        continuity_status="consistent",
    )


def generate_worldline_days_for_range(
    report: ScenarioReport,
    *,
    start_date: date,
    end_date: date,
    previous_state: WorldlineState,
    generation_source: str,
    chunk_index: int | None,
    chunk_status: str,
    quality_notes: list[str],
) -> list[WorldlineDay]:
    language = report.language or "en"
    agent_categories = {agent.agent_id: agent.category for agent in report.agents}
    asset_support_by_date = _asset_support_by_date(report)
    snapshots = [
        snapshot
        for snapshot in report.daily_timeline
        if start_date <= snapshot.date <= end_date
    ]
    days: list[WorldlineDay] = []
    current_state = previous_state
    final_date = report.daily_timeline[-1].date if report.daily_timeline else end_date

    for snapshot in snapshots:
        world_state_before = current_state
        agent_events = [
            _build_agent_event(
                snapshot,
                agent_state.agent_id,
                agent_state.agent_name,
                agent_categories.get(agent_state.agent_id, "unknown"),
                asset_support_by_date.get(snapshot.date.isoformat()),
                language=language,
            )
            for agent_state in snapshot.agent_states
        ]
        causal_links = _build_causal_links(snapshot, agent_events, language=language)
        world_state_after = _apply_events(
            world_state_before,
            snapshot,
            agent_events,
            asset_support_by_date.get(snapshot.date.isoformat()),
            language=language,
        )
        next_day_update = (
            (
                "模擬範圍已結束，不再生成下一日。"
                if language == "zh-Hant"
                else "End of simulated horizon; no next day is generated."
            )
            if snapshot.date == final_date
            else _next_day_update(snapshot, world_state_after, language=language)
        )
        days.append(
            WorldlineDay(
                date=snapshot.date,
                day_index=snapshot.day_index,
                generation_source=generation_source,
                chunk_index=chunk_index,
                chunk_status=chunk_status,
                quality_notes=quality_notes,
                input_context_summary=_input_context_summary(snapshot, language=language),
                world_state_before=world_state_before,
                agent_events=agent_events,
                causal_links=causal_links,
                next_day_update=next_day_update,
                world_state_after=world_state_after,
                disclaimer=(
                    WORLDLINE_DISCLAIMER_ZH_HANT
                    if language == "zh-Hant"
                    else WORLDLINE_DISCLAIMER
                ),
            )
        )
        current_state = world_state_after
    return days


def _asset_support_by_date(report: ScenarioReport) -> dict[str, float]:
    indicators = report.llm_report.asset_stress_indicators if report.llm_report else []
    values_by_date: dict[str, list[float]] = {}
    for indicator in indicators:
        values_by_date.setdefault(indicator.date.isoformat(), []).append(
            indicator.sentiment_stress_support
        )
    return {
        date_key: sum(values) / len(values)
        for date_key, values in values_by_date.items()
        if values
    }


def _initial_state(
    snapshot: DailyScenarioSnapshot,
    asset_support: dict[str, float],
    *,
    language: str,
) -> WorldlineState:
    stress = _pressure_from_regime(
        snapshot.research_signals.stress_regime,
        {"stress": 0.72, "elevated": 0.62, "watchful": 0.48, "calm": 0.3},
        default=0.42,
    )
    volatility = _pressure_from_regime(
        snapshot.research_signals.volatility_regime,
        {"expanded": 0.64, "normal": 0.42, "compressed": 0.28},
        default=0.4,
    )
    liquidity = _pressure_from_regime(
        snapshot.research_signals.liquidity_regime,
        {"thin": 0.68, "selective": 0.54, "orderly": 0.3},
        default=0.4,
    )
    support = asset_support.get(snapshot.date.isoformat(), 50.0)
    narrative = 0.45
    if snapshot.research_signals.astro_activity in {"high", "medium"}:
        narrative += 0.12
    if support < 35:
        narrative += 0.1
    elif support > 66:
        narrative -= 0.06
    return _state(
        narrative_pressure=narrative,
        leverage_pressure=0.4 + volatility * 0.2,
        liquidity_pressure=liquidity,
        volatility_pressure=volatility,
        stress_pressure=stress,
        notes=[
            (
                "初始狀態由每日研究訊號與資產支撐脈絡建立。"
                if language == "zh-Hant"
                else "Initial state seeded from daily research signals and asset support context."
            )
        ],
    )


def _pressure_from_regime(
    value: str,
    mapping: dict[str, float],
    *,
    default: float,
) -> float:
    return mapping.get(value, default)


def _build_agent_event(
    snapshot: DailyScenarioSnapshot,
    agent_id: str,
    agent_name: str,
    category: str,
    asset_support: float | None,
    *,
    language: str,
) -> WorldlineAgentEvent:
    context_scores = _context_scores(snapshot, asset_support)
    category_scores = _category_scores(category)
    scores = {
        key: clamp_delta(context_scores.get(key, 0) + category_scores.get(key, 0))
        for key in (
            "sentiment_delta",
            "narrative_pressure_delta",
            "leverage_pressure_delta",
            "liquidity_pressure_delta",
            "volatility_pressure_delta",
            "stress_pressure_delta",
        )
    }
    if language == "zh-Hant":
        support_note = (
            "當日有可用的 LLM 資產支撐指標。"
            if asset_support is not None
            else "當日沒有可用的 LLM 資產支撐指標。"
        )
        what_happened = (
            f"{agent_name} 在模擬路徑中回應了"
            f"{_regime_text(snapshot.research_signals.stress_regime, language)}壓力、"
            f"{_regime_text(snapshot.research_signals.volatility_regime, language)}波動，"
            f"以及{_regime_text(snapshot.research_signals.liquidity_regime, language)}流動性。"
        )
        why_it_happened = (
            f"每日脈絡的資料品質為{_regime_text(snapshot.research_signals.data_quality, language)}，"
            f"天象活動為{_regime_text(snapshot.research_signals.astro_activity, language)}。"
            f"{support_note}"
        )
        caveats = ["確定性 mock 群體事件，不是已觀測的市場行動。", "僅為模擬因果鏈，不是真實因果。"]
    else:
        support_note = (
            "LLM asset support metric is available for this day."
            if asset_support is not None
            else "No LLM asset support metric is available for this day."
        )
        what_happened = (
            f"{agent_name} reacted to {snapshot.research_signals.stress_regime} stress, "
            f"{snapshot.research_signals.volatility_regime} volatility, and "
            f"{snapshot.research_signals.liquidity_regime} liquidity in the simulated path."
        )
        why_it_happened = (
            f"The daily context carried {snapshot.research_signals.data_quality} data quality "
            f"and astro activity {snapshot.research_signals.astro_activity}. {support_note}"
        )
        caveats = [
            "Deterministic mock agent event; not an observed market action.",
            "Simulated causal link only; not true causality.",
        ]
    return WorldlineAgentEvent(
        agent_id=agent_id,
        agent_name=agent_name,
        what_happened=what_happened,
        why_it_happened=why_it_happened,
        impact_on_tomorrow=_impact_on_tomorrow(category, scores, language=language),
        impact_scores=WorldlineImpactScores(**scores),
        confidence="low_mock_confidence",
        caveats=caveats,
    )


def _context_scores(
    snapshot: DailyScenarioSnapshot,
    asset_support: float | None,
) -> dict[str, int]:
    stress = snapshot.research_signals.stress_regime
    volatility = snapshot.research_signals.volatility_regime
    liquidity = snapshot.research_signals.liquidity_regime
    astro = snapshot.research_signals.astro_activity
    scores = {
        "sentiment_delta": 0,
        "narrative_pressure_delta": 0,
        "leverage_pressure_delta": 0,
        "liquidity_pressure_delta": 0,
        "volatility_pressure_delta": 0,
        "stress_pressure_delta": 0,
    }
    if stress == "stress":
        scores["stress_pressure_delta"] += 1
        scores["volatility_pressure_delta"] += 1
        scores["sentiment_delta"] += 1
    elif stress == "elevated":
        scores["stress_pressure_delta"] += 1
    if volatility == "expanded":
        scores["volatility_pressure_delta"] += 1
    elif volatility == "compressed":
        scores["volatility_pressure_delta"] -= 1
    if liquidity in {"thin", "selective"}:
        scores["liquidity_pressure_delta"] += 1
    if astro == "high":
        scores["narrative_pressure_delta"] += 1
    if asset_support is not None:
        if asset_support < 35:
            scores["sentiment_delta"] += 1
            scores["stress_pressure_delta"] += 1
        elif asset_support > 66:
            scores["sentiment_delta"] -= 1
            scores["stress_pressure_delta"] -= 1
    return scores


def _category_scores(category: str) -> dict[str, int]:
    if category == "retail":
        return {"narrative_pressure_delta": 1, "sentiment_delta": 1}
    if category == "trading":
        return {"leverage_pressure_delta": 1, "volatility_pressure_delta": 1}
    if category == "institutional":
        return {"stress_pressure_delta": 1, "liquidity_pressure_delta": 1}
    if category == "company_type":
        return {"liquidity_pressure_delta": 1, "sentiment_delta": 0}
    return {}


def _impact_on_tomorrow(category: str, scores: dict[str, int], *, language: str) -> str:
    pressure_keys = [
        key.replace("_delta", "")
        for key, value in scores.items()
        if value > 0 and key != "sentiment_delta"
    ]
    if language == "zh-Hant":
        pressure_labels = [_pressure_key_text(key, language) for key in pressure_keys]
        if not pressure_labels:
            return "下一日推演維持較平穩的狀態，沒有主要壓力上升。"
        joined = "、".join(pressure_labels)
        if category == "trading":
            return f"明日情境將更留意{joined}。"
        if category == "retail":
            return f"明日情境對{joined}相關敘事會更敏感。"
        return f"明日情境將加強檢視{joined}。"
    if not pressure_keys:
        return "Sets up a steadier next-day rehearsal state with no major pressure increase."
    if category == "trading":
        return f"Sets up tomorrow with more attention to {', '.join(pressure_keys)}."
    if category == "retail":
        return f"Sets up tomorrow with more narrative sensitivity around {', '.join(pressure_keys)}."
    return f"Sets up tomorrow with more risk review around {', '.join(pressure_keys)}."


def _build_causal_links(
    snapshot: DailyScenarioSnapshot,
    agent_events: list[WorldlineAgentEvent],
    *,
    language: str,
) -> list[WorldlineCausalLink]:
    zh_hant = language == "zh-Hant"
    links = [
        WorldlineCausalLink(
            source="daily_context",
            target="agent_events",
            description=(
                "每日壓力、波動、流動性及天象標籤被映射為模擬群體反應。"
                if zh_hant
                else (
                    "Daily stress, volatility, liquidity, and astro tags are mapped into "
                    "simulated agent reactions."
                )
            ),
            strength="medium",
            caveats=[
                "僅為模擬因果鏈，不是真實因果的證據。"
                if zh_hant
                else "Simulated causal link only; not evidence of true causality."
            ],
        )
    ]
    if snapshot.research_signals.stress_regime in {"stress", "elevated"}:
        links.append(
            WorldlineCausalLink(
                source="stress_regime",
                target="next_day_stress_pressure",
                description=(
                    "在 mock 路徑中，壓力升高標籤會提高下一日壓力指標。"
                    if zh_hant
                    else "Elevated stress labels raise next-day stress pressure in the mock path."
                ),
                strength="medium",
                caveats=["僅為情境路徑機制。" if zh_hant else "Scenario path mechanic only."],
            )
        )
    if any(event.impact_scores.narrative_pressure_delta > 0 for event in agent_events):
        links.append(
            WorldlineCausalLink(
                source="agent_narrative_reaction",
                target="next_day_narrative_pressure",
                description=(
                    "對敘事敏感的群體事件會提高明日的敘事壓力。"
                    if zh_hant
                    else "Narrative-sensitive agent events increase tomorrow's narrative pressure."
                ),
                strength="low_to_medium",
                caveats=[
                    "僅為未來情境推演，不是交易訊號。"
                    if zh_hant
                    else "Future rehearsal only; not a trading signal."
                ],
            )
        )
    return links


def _apply_events(
    state: WorldlineState,
    snapshot: DailyScenarioSnapshot,
    agent_events: list[WorldlineAgentEvent],
    asset_support: float | None,
    *,
    language: str,
) -> WorldlineState:
    total = {
        "sentiment_delta": 0,
        "narrative_pressure_delta": 0,
        "leverage_pressure_delta": 0,
        "liquidity_pressure_delta": 0,
        "volatility_pressure_delta": 0,
        "stress_pressure_delta": 0,
    }
    for event in agent_events:
        for key in total:
            total[key] += getattr(event.impact_scores, key)
    divisor = max(len(agent_events), 1)
    support_adjustment = 0.0
    if asset_support is not None:
        support_adjustment = (50.0 - asset_support) / 1000.0

    return _state(
        narrative_pressure=(
            state.narrative_pressure
            + total["narrative_pressure_delta"] / divisor * 0.05
            + support_adjustment
        ),
        leverage_pressure=state.leverage_pressure + total["leverage_pressure_delta"] / divisor * 0.045,
        liquidity_pressure=state.liquidity_pressure + total["liquidity_pressure_delta"] / divisor * 0.045,
        volatility_pressure=state.volatility_pressure + total["volatility_pressure_delta"] / divisor * 0.045,
        stress_pressure=state.stress_pressure + total["stress_pressure_delta"] / divisor * 0.045,
        notes=(
            [
                f"已根據 {len(agent_events)} 個模擬群體事件更新。",
                f"每日脈絡：壓力={_regime_text(snapshot.research_signals.stress_regime, language)}，"
                f"波動={_regime_text(snapshot.research_signals.volatility_regime, language)}，"
                f"流動性={_regime_text(snapshot.research_signals.liquidity_regime, language)}。",
            ]
            if language == "zh-Hant"
            else [
                f"Updated from {len(agent_events)} simulated agent events.",
                f"Daily context: stress={snapshot.research_signals.stress_regime}, "
                f"volatility={snapshot.research_signals.volatility_regime}, "
                f"liquidity={snapshot.research_signals.liquidity_regime}.",
            ]
        ),
    )


def _state(
    *,
    narrative_pressure: float,
    leverage_pressure: float,
    liquidity_pressure: float,
    volatility_pressure: float,
    stress_pressure: float,
    notes: list[str],
) -> WorldlineState:
    values = {
        "narrative_pressure": clamp_pressure(narrative_pressure),
        "leverage_pressure": clamp_pressure(leverage_pressure),
        "liquidity_pressure": clamp_pressure(liquidity_pressure),
        "volatility_pressure": clamp_pressure(volatility_pressure),
        "stress_pressure": clamp_pressure(stress_pressure),
    }
    average_pressure = sum(values.values()) / len(values)
    if average_pressure >= 0.66:
        sentiment_state = "stressed"
    elif average_pressure >= 0.45:
        sentiment_state = "watchful"
    else:
        sentiment_state = "calm"
    return WorldlineState(
        sentiment_state=sentiment_state,
        regime_label=_regime_label(values),
        notes=notes,
        **values,
    )


def _regime_label(values: dict[str, float]) -> str:
    if values["stress_pressure"] >= 0.65 and values["liquidity_pressure"] >= 0.55:
        return "stress_liquidity_watch"
    if values["volatility_pressure"] >= 0.65:
        return "volatility_expansion_watch"
    if values["narrative_pressure"] >= 0.65:
        return "narrative_pressure_watch"
    return "balanced_rehearsal_path"


def _input_context_summary(snapshot: DailyScenarioSnapshot, *, language: str) -> str:
    if language == "zh-Hant":
        return (
            f"{snapshot.date.isoformat()} 脈絡："
            f"壓力={_regime_text(snapshot.research_signals.stress_regime, language)}，"
            f"波動={_regime_text(snapshot.research_signals.volatility_regime, language)}，"
            f"流動性={_regime_text(snapshot.research_signals.liquidity_regime, language)}，"
            f"天象活動={_regime_text(snapshot.research_signals.astro_activity, language)}，"
            f"資料品質={_regime_text(snapshot.research_signals.data_quality, language)}。"
        )
    return (
        f"{snapshot.date.isoformat()} context: stress={snapshot.research_signals.stress_regime}, "
        f"volatility={snapshot.research_signals.volatility_regime}, "
        f"liquidity={snapshot.research_signals.liquidity_regime}, "
        f"astro_activity={snapshot.research_signals.astro_activity}, "
        f"data_quality={snapshot.research_signals.data_quality}."
    )


def _next_day_update(
    snapshot: DailyScenarioSnapshot,
    state: WorldlineState,
    *,
    language: str,
) -> str:
    if language == "zh-Hant":
        return (
            f"下一個模擬日由{_regime_text(state.sentiment_state, language)}情緒狀態開始，"
            f"情境標籤為{_regime_text(state.regime_label, language)}；"
            f"前一日 {snapshot.date.isoformat()} 為群體關注提供推演基線。"
        )
    return (
        f"The next simulated day starts from {state.sentiment_state} sentiment with "
        f"regime label {state.regime_label}; prior day {snapshot.date.isoformat()} "
        "sets the rehearsal baseline for agent attention."
    )


def _regime_text(value: str | None, language: str) -> str:
    if language != "zh-Hant" or value is None:
        return value or "unknown"
    return {
        "stress": "高壓",
        "elevated": "升高",
        "watchful": "觀望警戒",
        "calm": "平穩",
        "expanded": "擴張",
        "compressed": "壓縮",
        "normal": "正常",
        "thin": "偏薄",
        "selective": "選擇性",
        "orderly": "有序",
        "high": "高",
        "medium": "中",
        "low": "低",
        "stressed": "承壓",
        "computed_ephemeris_available": "可計算星曆資料可用",
        "local_research_available": "本地研究資料可用",
        "placeholder_fallback": "佔位資料回退",
        "future_placeholder": "未來佔位資料",
        "stress_liquidity_watch": "壓力與流動性警戒",
        "volatility_expansion_watch": "波動擴張警戒",
        "narrative_pressure_watch": "敘事壓力警戒",
        "balanced_rehearsal_path": "平衡推演路徑",
    }.get(value, value.replace("_", " "))


def _pressure_key_text(value: str, language: str) -> str:
    if language != "zh-Hant":
        return value
    return {
        "narrative_pressure": "敘事壓力",
        "leverage_pressure": "槓桿壓力",
        "liquidity_pressure": "流動性壓力",
        "volatility_pressure": "波動壓力",
        "stress_pressure": "壓力指標",
    }.get(value, value.replace("_", " "))
